Makefile. Util.up_to_date()

diff --git a/bin/roger b/bin/roger
--- a/bin/roger
+++ b/bin/roger
@@ -4,7 +4,7 @@ set -e
 namespace=scox
 release=redisgraph
 image_repository=redislabs/redisgraph
-image_tag=2.2.4
+image_tag=edge
 
 # https://github.com/bitnami/charts/tree/master/bitnami/redis
 init () {
@@ -14,8 +14,10 @@ start () {
     helm install $release \
 	 --set image.repository=$image_repository \
 	 --set image.tag=$image_tag \
-	 --set master.command= \
-	 --set slave.command= \
+	 --set redis.command="redis-server" \
+	 --set redis.args="--loadmodule /usr/lib/redis/modules/redisgraph.so" \
+	 --set master.command="redis-server --loadmodule /usr/lib/redis/modules/redisgraph.so" \
+	 --set slave.command="redis-server --loadmodule /usr/lib/redis/modules/redisgraph.so" \
 	 --namespace=$namespace \
 	 bitnami/redis
 }
@@ -66,7 +68,7 @@ kgx () {
 	time roger --merge-kgx $*
     }
     schema () {
-	time roger --create-schema
+	time roger --create-schema $*
     }
     clean () {
 	schema () {
@@ -90,13 +92,17 @@ kgx () {
 
 bulk () {
     create () {
-	time roger --create-bulk
+	time roger --create-bulk $*
     }
     load () {
+	if [ "$1" == "--data-root" ]; then
+	    DATA_HOME=$2
+	    shift; shift;
+	fi
 	redis-cli GRAPH.DELETE $DB_NAME
-	nargs=$(echo data/bulk/nodes/* | sed -e 's, , --nodes ,g')
-	rargs=$(echo data/bulk/edges/* | sed -e 's, , --relations ,g')
-	do_load --nodes $nargs --relations $rargs
+	nargs=$(echo $DATA_HOME/bulk/nodes/* | sed -e 's, , --nodes ,g')
+	rargs=$(echo $DATA_HOME/bulk/edges/* | sed -e 's, , --relations ,g')
+	do_load --nodes $nargs --relations $rargs $*
     }
     do_load () {
 	echo deleting existing graph...
@@ -139,14 +145,38 @@ query () {
 }
 
 all () {
-    kgx clean all
-    bulk clean
+#    kgx clean all
+#    bulk clean
     kgx get
     kgx merge
     kgx schema
     bulk create
     bulk load
     validate
+}
+
+f () {
+# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
+PARAMS=""
+while (( "$#" )); do
+    case "$1" in
+	-d|--data-root)
+	    if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+		DATA_HOME=$2
+		shift 2
+	    else
+		echo "Error: Argument for $1 is missing" >&2
+		exit 1
+	    fi
+	    ;;
+	*) # preserve positional arguments
+	    PARAMS="$PARAMS $1"
+	    shift
+	    ;;
+    esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
 }
 
 $*
